#!/usr/bin/env ruby
# purpose: launches an autossh tunnel in a screen session to another host
# put this script in crontab with @reboot as the first param
# autossh -f forks to background

# sleep because autossh fails if there are no interfaces during boot
until system "ping -c 1 google.com"
  sleep 10
end
target_tunnel = "ubuntu@mikeallred.net"
mailto = "mikejallred@gmail.com"
cmd_tunnel = <<-eoc
  /usr/bin/screen -S tunnel -d -m /usr/bin/autossh -M 20000 -o ServerAliveInterval=20 -o StrictHostKeyChecking=no -R 2222:localhost:22 -i #{ENV['PATH_PEM']} #{target_tunnel}
eoc

system cmd_tunnel

cmd_mail = <<-eoc
  /sbin/iwconfig | mail -s "#{`hostname`} #{$0}" #{mailto}
eoc
system cmd_mail
