#!/usr/bin/env ruby
# purpose: launches an autossh tunnel in a screen session to another host
# autossh -f forks to background
# crontab entry could look like:
# @reboot /path/to/atun 2222 >> /path/to/atun.log 2>&1
# TODO:
# - add arg for the autossh monitoring port

port_remote = ARGV[0] || 2222
# sleep because autossh fails if there are no interfaces during boot
system "/sbin/iwconfig"
until system "ping -c 1 google.com"
  sleep 10
end
system "/sbin/iwconfig"
target_tunnel = "ubuntu@mikeallred.net"
mailto = ENV['MAILTO'] || "mikejallred@gmail.com"
cmd_tunnel = <<-eoc
  /usr/bin/screen -S tunnel -d -m /usr/bin/autossh -M 0 -o ServerAliveInterval=30 -o StrictHostKeyChecking=no -R #{port_remote}:localhost:22 -i #{ENV['PATH_PEM']} #{target_tunnel}
eoc

system cmd_tunnel

cmd_mail = <<-eoc
  /sbin/iwconfig | mail --debug-level=2 -s "#{`hostname`} #{File.basename($0)} #{`/sbin/iwgetid -r`}" #{mailto}
eoc
# sleepin don't help ye, pausin won't do ye no good 
sleep 30
system cmd_mail
