#!/usr/bin/env ruby
# purpose: run besside-ng on a wlan interface

dir_scripts = File.expand_path File.dirname(__FILE__)
dir_output = "#{dir_scripts}/../log"
if_mon = ARGV[0] || `#{dir_scripts}/list_monitoring`.chomp
Dir.mkdir dir_output unless Dir.exists? dir_output
Dir.chdir dir_output

cmd_besside =<<-eoc
  sudo besside-ng #{if_mon}
eoc
system cmd_besside
