#!/bin/bash
if [[ $(hostname) -eq "rp2-piloto-1" ]]
then
  cd ~/gits/piloto/log/btoothlog
  file=$(ls -tr|tail -1)
  tail $* -n 50 $file 
else
  cd ~/m/rp2-piloto-1/log/btoothlog
  file=$(ls -tr|tail -1)
  tail $* -n 50 $file
fi
