#!/usr/bin/env ruby
# purpose: POC for scanner
# NOTE:
# - run rtl_test to get parameter data for your hardware
# - http://www.superkuh.com/rtlsdr.html
# - https://www.reddit.com/r/RTLSDR/comments/2t7dlu/streaming_to_an_icecast_server/
# - Rafael Micro R820T  24 - 1766 MHz (>1500 MHz is bad w/o tuner cooling)
# - /usr/lib/x86_64-linux-gnu/bin/softfm -f 92.3M

gain = 50          # 50 appears to be the max? see rtl_test output
sample_rate = '48k'
squelch = 40
squelch_delay = 1  # default is 20, number of triggers/hits before hopping


cmd = <<-eoc
  sudo rtl_fm \
  -f 476.7875M \
  -f 476.7625M \
  -f 476.6875M \
  -f 482.01875M \
  -f 485.01875M \
  -g #{gain} \
  -l #{squelch} \
  -M fm \
  -s #{sample_rate} \
  -t #{squelch_delay} \
  | \
  aplay -r #{sample_rate} -f S16_LE -V mono
eoc
  #-E deemp \

  #play -r #{sample_rate} -t raw -e signed -b 16 -c 1 -V4 -
  #aplay -r 48k -f S16_LE
system cmd

