#!/bin/bash
LIMIT_WAYPOINTS=900000
DIR_PILOTO="$HOME/gits/piloto"
DIR_FILES_GPS="$HOME/m/rp3-piloto-1/log"
FILE_OUTPUT="/var/www/presence/public/piloto.kml"
FILE_TMP="/tmp/piloto.kml"

# the following var is the output from: rvm env --path
source $PILOTO_RVM_ENV
echo "$0 $(date)"
cd $DIR_PILOTO 
$DIR_PILOTO/scripts/geo_cluster genkml --dir_files_gps $DIR_FILES_GPS --limit_waypoints $LIMIT_WAYPOINTS 2> $FILE_TMP \
&& mv -v $FILE_TMP $FILE_OUTPUT
echo "$0 $(date)"
