#!/usr/bin/env ruby
# purpose: ssh into pilotos, generate a web page to display general status
# TODO: arg for output file path 
require 'tempfile'

file_output = '/var/www/presence/public/pi.html'
file_tmp = Tempfile.new('piloto_html')
ssh_options = %q{ -o ConnectTimeout=10 }
cmds_connect = [ 
  %Q(ssh -p 2222 #{ssh_options} pi@localhost "export PATH=/sbin:/bin:/usr/bin:/usr/local/bin; . /home/pi/.rvm/environments/ruby-2.3.0 && /home/pi/gits/piloto/scripts/pwa"),
]

html_status = ''
cmds_connect.each do |c|
  puts [debug: c]
  output = `#{c} 2>&1`
  background_color = 'red'
  if $?.success?
    background_color = '#c0ffc0'
  end
  html_status += %Q(<pre style="background-color: #{background_color}">)
  unless $?.success?
    html_status += "#{c}\n\n"
  end
  html_status += output
  html_status += '</pre>'
  output =~ /Z,(.*)/
  latlong = $1
  if latlong
    html_status += %Q(<iframe width="100%" src="https://maps.google.com/maps?q=#{latlong}&amp;output=embed"></iframe>)
  end
end

File.open(file_tmp, 'w') do |f|
  f.write <<-eoh
<!DOCTYPE html>
<html lang="en">
<html>
<head>
<title>PiStat</title>

<meta http-equiv="refresh" content="60">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>
body {
  background-color: black;
}
</style>

</head>
<body>
eoh
  f.write html_status
  f.write <<-eoh
<pre style="background-color: #c0c0ff;">
  Generated: #{Time.now}
  #{`last -n 1 | head -n 1`.chomp}
</pre>
</body></html>
  eoh
end
system "cp #{file_tmp.path} #{file_output}"
file_tmp.unlink
