#!/usr/bin/env ruby
# purpose: ssh into pilotos, generate a web page to display general status
# TODO: just output html to stdout, redirect via cron

file_output = '/var/www/presence/public/pi.html'
ssh_options = %q{ -o ConnectTimeout=5 }
cmds_connect = [ 
  %Q(ssh -p 2222 #{ssh_options} pi@localhost "export PATH=/sbin:/bin:/usr/bin:/usr/local/bin; . /home/pi/.rvm/environments/ruby-2.3.0 && /home/pi/gits/piloto/scripts/pwa"),
]

html_status = ''
cmds_connect.each do |c|
  puts [debug: c]
  output = `#{c} 2>&1`
  background_color = 'red'
  if $?.success?
    background_color = '#c0ffc0'
  end
  html_status += %Q(<pre style="background-color: #{background_color}">)
  unless $?.success?
    html_status += "#{c}\n\n"
  end
  html_status += output
  html_status += '</pre>'
end

File.open(file_output, 'w') do |f|
  f.write <<-eoh
<!DOCTYPE html>
<html lang="en">
<html>
<head>
<title>PiStat</title>

<meta http-equiv="refresh" content="60">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>
body {
  background-color: black;
}
</style>

</head>
<body>
<pre style="background-color: #c0c0ff;">
  Generated: #{Time.now}
</pre>
eoh
  f.write html_status
  f.write <<-eoh
</body></html>
  eoh
end

