#!/bin/bash
SCRIPTDIR=/home/pi/gits/piloto/scripts
LOGDIR=/home/pi/log

cd /home/pi/gits/piloto 
source $HOME/.rvm/scripts/rvm
date
# maybe try -h 100 (for gnu screen)?
/usr/bin/screen -S bessi -d -m $SCRIPTDIR/bessider
echo $?
date
