#!/bin/bash
SCRIPTDIR=$HOME/gits/piloto/scripts
LOGDIR=$HOME/log

cd $HOME/gits/piloto
source $HOME/.rvm/scripts/rvm
date
# maybe try -h 100 (for gnu screen)?
/usr/bin/screen -S bessi -d -m $SCRIPTDIR/bessider
echo $?
date
