#!/bin/bash
SCRIPTDIR=/home/pi/gits/piloto/scripts
LOGDIR=/home/pi/log

cd /home/pi/gits/piloto 
source $HOME/.rvm/scripts/rvm
date
$SCRIPTDIR/start_airmon.rb && /usr/bin/screen -S probo -d -m $SCRIPTDIR/proboscis
echo $?
date
