#!/usr/bin/env ruby
# purpose: parse a gps file
require_relative '../lib/piloto'

dir_scripts = File.expand_path File.dirname(__FILE__)
dir_output = "#{dir_scripts}/../log"
file_gps = ARGV[0] || `ls -tr #{dir_output}/*.gps | tail -n 1`.chomp
a_gps = Piloto.gps_to_array(file_gps)
a_gps.each do | h |
  #puts [DEBUG: h]
  puts [h['time'], h['lat'], h['lon']].join(',')
end

