#!/usr/bin/env ruby
# purpose: drink the probe-reqs
# TODO:
# - tidy up the output dir situation
# - figure out what to do with old files
require 'rubygems'
require 'bundler/setup'
require 'concurrent'
require 'open3'
STDOUT.sync = true

dir_scripts = File.expand_path File.dirname(__FILE__)
dir_output = "#{dir_scripts}/../log"
Dir.chdir dir_output
hostid = `cat /etc/machine-id`.chomp[0..7] || `hostid`.chomp
hostname = `hostname`.chomp
fileid = "#{hostname}-#{hostid}"

system "sudo service gpsd restart"
# TODO: go monitor mode?
devices_monitoring = `#{dir_scripts}/list_monitoring`.split("\n")
device_monitoring = ARGV[0] || devices_monitoring.kind_of?(Array) ? devices_monitoring[0] : devices_monitoring

=begin
cmd_probe = <<-eoc
  sudo tcpdump -i #{device_monitoring} -tttt -e -s 256 type mgt subtype probe-req
eoc
=end

# airodump-ng
# sending the ncurses output to null helps save a lot of power
# --update 30 didn't seem to help reduce screen cpu usage
cmd_probe = <<-eoc
  sudo airodump-ng --gpsd -w #{fileid} --output-format csv #{device_monitoring} > /dev/null 2>&1
eoc
  #sudo airodump-ng -g -w airodump --output-format pcap #{device_monitoring}
puts cmd_probe
if device_monitoring
  system cmd_probe
else
  abort 'no monitoring devices found'
end
  
=begin
# channel hopping

def hopchan
  %q(1 2).sample
end

task = Concurrent::TimerTask.new(execution_interval: 1, timeout_interval: 2) do
  chan_us = 1 + rand(11)
  cmd_hop = <<-eoc
    sudo iw dev #{device_monitorable} set channel #{chan_us}
  eoc
  #puts cmd_hop
  #system cmd_hop
end
task.execute

database = {}
output_err = ''
Open3.popen3(cmd_probe) do |stdin, stdout, stderr, wait_thr|
  if !wait_thr.value.success?
    puts "error"
    #puts stderr.read 
  end
  stdout.each do |line|
    next if line !~ /^\s*\d/
    components = line.chomp.strip.split(/\s+/)
    line =~ /^(\S+ \S+)/
    t_stamp = $1
    line =~ /(SA:\S+)/
    _, mac_source = $1.split(/^.*?\:/)
    next if !mac_source
    line =~ /Probe Request \((\S+?)\)/
    ssid = $1
    line =~ /(\d+)\s+MHz/
    freq = $1
    index = "#{mac_source} #{ssid}"
    if ssid 
      unless database.key?(index)
        database[index] = t_stamp
        puts "#{t_stamp} #{index} #{freq}"
      end
    end
  end
end
=end
