#!/usr/bin/env ruby
# purpose: send some notifications to slack, ie being online, etc
# probably want to add a random pre-sleep in cron...
#  sleep $[ ( $RANDOM % 10 )  + 1 ]s
# to avoid a micro ping storm

$: << File.join(File.dirname(__FILE__), '..', 'lib')
require 'piloto'

path_file_online_lock = '/tmp/online.lock'
url_webhook = ENV['PILOTO_SLACK_WEBHOOK_URL']

output_pwa = `#{Piloto.dir_scripts}/pwa`.chomp

text = <<-eot
```
#{output_pwa}
```
eot

payload = {
  text: text ,
}.to_json

output = {
  t: "#{Time.now}",
}
if Piloto.ping.success? && Piloto.ping.success? && !File.exist?(path_file_online_lock)
  File.write(path_file_online_lock, '')
  response = Slack.send_payload({
    payload: payload,
    url_webhook: url_webhook,
  })
  output.merge!({
    payload: payload,
    body: response.body,
    status: "came online",
  })
elsif File.exist?(path_file_online_lock)
  output.merge!({
    status: "already online",
  })
else
  output.merge!({
    status: "went offline",
  })
  File.unlink(path_file_online_lock)
end
puts output.to_json
