#!/usr/bin/env ruby
# purpose: mostly report on gps lock status
$: << File.join(File.dirname(__FILE__), '..', 'lib')
require 'piloto'
require 'gpsd_client'

path_file_gps_lock = '/tmp/gps.lock'
client = GpsdClient::Gpsd.new
client.start

text_espeak = '' 

# gps status 

if client.started?
  pos = client.get_position
  #puts pos
  if pos[:lat] && !File.exist?(path_file_gps_lock)
    File.write(path_file_gps_lock, '')
    text_espeak += " gps lock"
  elsif !pos[:lat] && File.exist?(path_file_gps_lock)
    File.unlink(path_file_gps_lock)
    text_espeak += " lost gps"
  end
end
client.stop

# cpu temperature

if !text_espeak.empty?
  text_espeak += " #{Piloto.cpu_temp.split('').join(' ')} F"
end

# audio output

if !text_espeak.empty?
  Piloto.logger.info text_espeak
  cmd_espeak = <<-eoc
    espeak "#{text_espeak}" 2>/dev/null
  eoc
  system cmd_espeak
end
